### ISSUE TITLE
No triggering

### ISSUE THREAD

**Issue by bitbreakr** [james-barrow/golang-ipc#1]
Hello, 

I have been implementing this in 2 go executables

server.go:

```go
package main

import (
	"fmt"
	"log"

	ipc "github.com/james-barrow/golang-ipc"
)

type PowerManagementCommand struct {
	Command string
}

func main() {
	sc, err := ipc.StartServer("echo", nil)
	if err != nil {
		log.Println(err)
		return
	}

	for {

		data, err := sc.Read()

		if err == nil {
			fmt.Print("Recieedede")
			log.Println("Server recieved: "+string(data.Data)+" - Message type: ", data.MsgType)
		} else {
			log.Println(err)
			break
		}
	}
}
```

client.go

```go
package main

import (
	"log"

	ipc "github.com/james-barrow/golang-ipc"
)

func main() {
	cc, err := ipc.StartClient("echo", nil)
	if err != nil {
		log.Println(err)
		return
	}

	_ = cc.Write(5, []byte("Message from client"))
}
```

I confirm that a socket is created at /tmp/echo.sock, but everytime  client.go is executed, nothing happens on server.go

Error returned from the client is:

```bash
Message exceeds maximum message length% 
```

Is there something I'm missing?

Thanks in advance

**Comment by james-barrow** [comment]
Hello,

I spotted two things:

- The idea is the connection is by-directional so you need the to have the read function active on the client. 
- It takes a moment for the connection be established so the client needs to wait a little bit before sending the message and the program needs to keep running until the message has been received by the server. 

The "Message exceeds maximum message length" on the client write function is a bug it should be say there's no connection.

**Comment by bitbreakr** [comment]
Thanks for your reply, I had to write my own package because of lack of time.
