### ISSUE TITLE
from example, if i remove "time.Sleep(time.Second)" <-- basically make it send as fast as possible, doesnt work

### ISSUE THREAD

**Issue by kolinfluence** [james-barrow/golang-ipc#12]
from example, if i remove "time.Sleep(time.Second)" <-- basically make it send as fast as possible, receiver end will receive nothing.
why?

**Comment by james-barrow** [comment]
I created the example a little while back and I think it needs a little work to make it better :)

The example opens the server and client on separate go routines so the sleep timers are there to make sure both sides have started up properly before trying to send messages.
