### ISSUE TITLE
types.go Status Consts

### ISSUE THREAD

**Issue by yjawhar** [james-barrow/golang-ipc#15]
This is not a bug, but idiomatic way to declare enumerated constant using iota.

https://go.dev/doc/effective_go#constants

`const (

	// NotConnected - 0
	NotConnected Status = iota
	// Listening - 1
	Listening
	// Connecting - 2
	Connecting
	// Connected - 3
	Connected
	// ReConnecting - 4
	ReConnecting
	// Closed - 5
	Closed
	// Closing - 6
	Closing
	// Error - 7
	Error
	// Timeout - 8
	Timeout
	// Disconnected - 9
	Disconnected
)`

**Comment by james-barrow** [comment]
I've tided this up.
